### ISSUE TITLE
Build fails with Boost v1.66.0

### ISSUE THREAD

**Issue by RobWillis** [nekipelov/redisclient#55]
Build fails when compiling with the latest boost (v1.66.0)
I was using boost v1.62 previously and compile worked fine on that version.

Error I'm seeing (compiled with gcc7.3 + boost1.66.0):

In file included from /redisclient/src/redisclient/redissyncclient.h:16:0,
                 from /redisclient/src/redisclient/impl/pipeline.cpp:11:
/redisclient/src/redisclient/impl/redisclientimpl.h:86:5: error: invalid use of template-name 'boost::asio::strand' without an argument list
     boost::asio::strand strand;
     ^~~~~
/redisclient/src/redisclient/impl/redisclientimpl.h:86:5: note: class template argument deduction is only available with -std=c++1z or -std=gnu++1z

**Comment by nekipelov** [comment]
What version of the redisclient do you use?

**Comment by RobWillis** [comment]
Version v0.6.0
I've attached a Dockerfile that replicates the build environment and the build error.
Copy the Dockerfile into an empty subdirectory and the build with:
docker build -f Dockerfile.txt -t redis .
It does take a while to build since it has to build boost first.

[Dockerfile.txt](https://github.com/nekipelov/redisclient/files/1775528/Dockerfile.txt)

**Comment by nekipelov** [comment]
Fixed in #53. Use new version v0.6.1.

**Comment by RobWillis** [comment]
I upgraded to v0.6.1 and it resolved the boost compile issue, but now it no longer builds static library  libredisclient.a like it did in v0.5 which is required for my use case.
The readme still implies it will automatically build the static lib and you have to pass in an option to tell it to build a shared lib.  Something changed from v0.5 when the static lib was the default.

Thanks for the help.

**Comment by RobWillis** [comment]
Ok figured it out.   Now have to add the -DBUILD_SHARED_LIBS=OFF option and the library has been renamed to libRedisClient.a from libredisclient.a.

Anyways, working now.

**Comment by RobWillis** [comment]
Sorry.  Still seeing issues when including this latest version in my project.  
Seeing this compile error:
/usr/local/include/redisclient/impl/redisasyncclient.cpp:12:41: fatal error: redisclient/impl/throwerror.h: No such file or directory
 #include "redisclient/impl/throwerror.h"

I built and installed the redis lib with this command sequence:

mkdir build
cd build
cmake  -DBUILD_SHARED_LIBS=OFF -DBUILD_TEST=OFF -DBUILD_EXAMPLES=OFF -DHEADER_ONLY=ON ..
 make
 make install

**Comment by nekipelov** [comment]
Fixd in a master branch.
